name: Build & Test PR

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
    PROJECT_NAME: Blazored.FluentValidation
    NETCORE_VERSION: '8.0.x'
    DOTNET_CONSOLE_ANSI_COLOR: true

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setting up .NET SDK ${{ env.NETCORE_VERSION }}...
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.NETCORE_VERSION }}

    - name: Restoring packages...
      run: dotnet restore

    - name: Building project...
      run: dotnet build --configuration Release --no-restore src/$PROJECT_NAME/$PROJECT_NAME.csproj

    - name: Running tests...
      run: dotnet test 